cras-config: Fix Wformat warnings reported by clang.
Fix a bunch of warnings reported by clang because of incorrect
format specifiers.

cras-config/aec_config.cc:390:4: error: format specifies type 'unsigned int'
but the argument has type 'size_t' (aka 'unsigned long') [-Werror,-Wformat]
                        config.suppressor.nearend_average_blocks);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cras-config/aec_config.cc:434:4: error: format specifies type 'double'
but the argument has type 'bool'  [-Werror,-Wformat]

And various other warnings.

BUG=chromium:958583
TEST=emerge-amd64-generic webrtc-apm works.

Change-Id: Ied98c83b5abf58ccd580307a55d825aacacdc833
Reviewed-on: https://chromium-review.googlesource.com/1592753
Commit-Ready: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Hsinyu Chao <hychao@chromium.org>